### PR TITLE
Update package-lock.json

### PR DESCRIPTION
**Pull request by null267**
Attempted to update dependencies.

### CODE REVIEW

**Comment by orzechowskid** [comment]
seems fine.  do the unit tests pass?

**Comment by null267** [comment]
PASS src/__tests__/utils.js (7.448s)
  the buildRegexFromOptions function
    √ builds a RegExp with 'prefix' at the start and 'suffix' at the end (3ms)
    √ builds a RegExp which captures a string with 'prefix' at the start and 'suffix' at the end when 'capturePrefixAndSuffix' is true
    √ throws if prefix or suffix is not provided (21ms)
  the getKeyForElement function
    √ returns the same value for two copies of the same object (1ms)
    √ returns different values for different objects
    √ returns different values for the same object with different indices (1ms)
    √ throws if 'element' or 'tokenIndex' are not provided (1ms)
  the regexProofString function
    √ escapes all regex-meaningful characters in the given string (1ms)
    √ returns the input string when no regex-meaningful characters are present (3ms)

PASS src/__tests__/postprocessor.js (7.573s)
  the ReactElementPostprocessor class definition
    √ sets the proper fields upon instantiation (3ms)
  the ReactElementPostprocessor process function
    √ replaces tokens with elements (4ms)
    √ replaces tokens with functional components (1ms)
    √ replaces tokens with elements when using custom delimiters (1ms)
    √ returns the original string when there's nothing to replace
    √ replaces unknown tokens with the empty string
    √ doesn't replace unknown tokens when keepUnknownVariables is true
    √ doesn't try anything funny if the interpolation value is not supported (1ms)
  the clone() helper function
    √ clones the provided element and gives it a key prop
    √ throws when not provided a key (4ms)
    √ throws when passed something that's not a React element (1ms)


Test Suites: 2 passed, 2 total
Tests:       20 passed, 20 total
Snapshots:   3 passed, 3 total
Time:        13.513s
Ran all test suites matching /src\\/i.

**Comment by null267** [comment]
All passed.  Just posted log.

**Comment by orzechowskid** [comment]
no need for the logs (which will become prohibitively long once you start working on larger projects), FYI - I trust you.

**Pull request merged**
